"""Funding-carry study over the recorded Hyperliquid corpus (2026-08-13).

Consumes ``mp-query carry`` JSONL -- one point per (hour, venue, symbol): the
OI-weighted funding rate plus the mark-vs-oracle basis in bps -- and renders
the carry-regime distribution + funding<->basis divergence into
``research/funding_carry_study_2026-08-13.md``.

Usage:
  py research/run_funding_carry_study.py --jsonl /tmp/carry.jsonl \
      [--out research/funding_carry_study_2026-08-13.md]

Deterministic: pure aggregation over the given points, no wall clock.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import statistics
import sys
from pathlib import Path

# Annualized funding bps from an HOURLY funding rate (Hyperliquid funds
# hourly): rate x 24 x 365 x 10^4.
HOURS_PER_YEAR = 24 * 365


def annualized_bps(rate: float) -> float:
    return rate * HOURS_PER_YEAR * 10_000.0


def regime_of(annualized: float) -> str:
    """Carry regime on annualized funding bps (thresholds in bps/yr)."""
    if annualized >= 2000:
        return "strong_positive"
    if annualized >= 500:
        return "positive"
    if annualized > -500:
        return "neutral"
    if annualized > -2000:
        return "negative"
    return "strong_negative"


REGIME_ORDER = [
    "strong_positive",
    "positive",
    "neutral",
    "negative",
    "strong_negative",
]


def pearson(xs: list[float], ys: list[float]) -> float | None:
    n = len(xs)
    if n < 2:
        return None
    mx, my = statistics.fmean(xs), statistics.fmean(ys)
    num = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    dx = sum((x - mx) ** 2 for x in xs) ** 0.5
    dy = sum((y - my) ** 2 for y in ys) ** 0.5
    if dx == 0 or dy == 0:
        return None
    return num / (dx * dy)


def day_of(ts_ns: int) -> str:
    return dt.datetime.fromtimestamp(ts_ns / 1e9, tz=dt.timezone.utc).strftime(
        "%Y-%m-%d"
    )


def load_points(path: Path) -> list[dict]:
    points = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        points.append(json.loads(line))
    return points


def analyze_symbol(points: list[dict]) -> dict:
    rates = [p["funding_rate"] for p in points]
    annualized = [annualized_bps(r) for r in rates]
    bases = [p["basis_bps"] for p in points if p["basis_bps"] is not None]
    pairs = [
        (p["funding_rate"], p["basis_bps"])
        for p in points
        if p["basis_bps"] is not None
    ]

    regimes: dict[str, int] = {r: 0 for r in REGIME_ORDER}
    for a in annualized:
        regimes[regime_of(a)] += 1

    by_day: dict[str, int] = {}
    for p in points:
        by_day[day_of(p["interval_ts_ns"])] = by_day.get(day_of(p["interval_ts_ns"]), 0) + 1

    return {
        "n": len(points),
        "n_with_basis": len(bases),
        "funding_mean_annual_bps": statistics.fmean(annualized),
        "funding_min_annual_bps": min(annualized),
        "funding_max_annual_bps": max(annualized),
        "funding_std_annual_bps": statistics.pstdev(annualized),
        "funding_mean_hourly": statistics.fmean(rates),
        "basis_mean_bps": statistics.fmean(bases) if bases else None,
        "basis_abs_mean_bps": statistics.fmean(abs(b) for b in bases) if bases else None,
        "basis_min_bps": min(bases) if bases else None,
        "basis_max_bps": max(bases) if bases else None,
        "basis_std_bps": statistics.pstdev(bases) if bases else None,
        "basis_positive_frac": (
            sum(1 for b in bases if b > 0) / len(bases) if bases else None
        ),
        "regimes": regimes,
        "by_day": dict(sorted(by_day.items())),
        "corr_funding_basis": pearson([p[0] for p in pairs], [p[1] for p in pairs])
        if pairs
        else None,
    }


def render(points: list[dict], out: Path) -> str:
    syms = sorted({p["symbol"] for p in points})
    all_rates = [annualized_bps(p["funding_rate"]) for p in points]
    all_bases = [p["basis_bps"] for p in points if p["basis_bps"] is not None]

    md: list[str] = []
    md.append("# Funding-Carry Study -- recorded Hyperliquid corpus")
    md.append("")
    md.append(f"Date: 2026-08-13 . Source: `mp-query carry --interval-secs 3600` "
              f"over the local raw corpus . {len(points)} hourly points, "
              f"{len({p['venue'] for p in points})} venue (hyperliquid). "
              "Generated by `research/run_funding_carry_study.py`.")
    md.append("")
    md.append("## Corpus")
    md.append("")
    md.append("| date | BTC hours | ETH hours |")
    md.append("|---|---|---|")
    all_days = sorted(
        {day_of(p["interval_ts_ns"]) for p in points}
    )
    for d in all_days:
        btc = sum(1 for p in points if day_of(p["interval_ts_ns"]) == d and p["symbol"] == "BTC")
        eth = sum(1 for p in points if day_of(p["interval_ts_ns"]) == d and p["symbol"] == "ETH")
        md.append(f"| {d} | {btc} | {eth} |")
    md.append("")

    for s in syms:
        sp = [p for p in points if p["symbol"] == s]
        a = analyze_symbol(sp)
        md.append(f"## {s}")
        md.append("")
        md.append(f"- **Hours:** {a['n']} (basis present in {a['n_with_basis']})")
        md.append(f"- **Funding:** hourly mean {a['funding_mean_hourly']:.6f} "
                  f"-> **annualized {a['funding_mean_annual_bps']:+.0f} bps/yr** "
                  f"(min {a['funding_min_annual_bps']:+.0f}, max {a['funding_max_annual_bps']:+.0f}, "
                  f"std {a['funding_std_annual_bps']:.0f})")
        md.append(f"- **Basis (mark - oracle):** mean {a['basis_mean_bps']:+.2f} bps, "
                  f"|mean| {a['basis_abs_mean_bps']:.2f}, "
                  f"min {a['basis_min_bps']:+.2f}, max {a['basis_max_bps']:+.2f}, "
                  f"std {a['basis_std_bps']:.2f}; "
                  f"{100.0 * (a['basis_positive_frac'] or 0):.0f}% of hours mark > oracle")
        md.append(f"- **Funding <-> basis correlation (Pearson):** "
                  f"{a['corr_funding_basis']:.2f}" if a["corr_funding_basis"] is not None
                  else "- **Funding <-> basis correlation (Pearson):** n/a (too few paired hours)")
        md.append("")
        md.append("### Carry-regime distribution (annualized funding)")
        md.append("")
        md.append("| regime | hours | % of day-hours | mean annualized (bps) |")
        md.append("|---|---|---|---|")
        for r in REGIME_ORDER:
            n = a["regimes"][r]
            if n == 0:
                md.append(f"| {r} | 0 | 0% | -- |")
                continue
            mean_ann = statistics.fmean(
                annualized_bps(p["funding_rate"])
                for p in sp
                if regime_of(annualized_bps(p["funding_rate"])) == r
            )
            md.append(f"| {r} | {n} | {100.0 * n / len(sp):.0f}% | {mean_ann:+.0f} |")
        md.append("")
        md.append("### Per-day mean funding (annualized bps)")
        md.append("")
        md.append("| date | mean bps/yr |")
        md.append("|---|---|")
        for d, _ in a["by_day"].items():
            mean = statistics.fmean(
                annualized_bps(p["funding_rate"])
                for p in sp
                if day_of(p["interval_ts_ns"]) == d
            )
            md.append(f"| {d} | {mean:+.0f} |")
        md.append("")

    md.append("## Combined (BTC + ETH)")
    md.append("")
    md.append(f"- **{len(all_rates)} hourly funding readings**: mean "
              f"{statistics.fmean(all_rates):+.0f} bps/yr, "
              f"min {min(all_rates):+.0f}, max {max(all_rates):+.0f}.")
    if all_bases:
        md.append(f"- **{len(all_bases)} basis readings**: mean "
                  f"{statistics.fmean(all_bases):+.2f} bps, "
                  f"|mean| {statistics.fmean(abs(b) for b in all_bases):.2f} bps.")
    md.append("")
    md.append("## Honest caveats")
    md.append("")
    md.append(f"- Corpus is 7 recording days (07-19, 07-21, 08-08..08-13) with partial")
    md.append(f"  days; {len(points)} hourly points ~ {100.0 * len(points) / (7 * 2 * 24):.0f}% of a")
    md.append(f"  full 7-day x 2-symbol x 24h grid. Regime fractions are indicative,")
    md.append(f"  not statistically settled.")
    md.append("- Hyperliquid funds hourly; the study uses the raw hourly rate (no")
    md.append("  8h normalization). OI weighting is trivial here (single venue).")
    md.append("- `mp-query carry` weights by OI contracts (Hyperliquid reports no")
    md.append("  notional); with a second venue reporting USD notional the two are")
    md.append("  never mixed (unit-class rule in `analytics::carry_series`).")
    md.append("- Basis is mark-vs-oracle (the venue's own index); it is NOT a")
    md.append("  tradable spot basis -- that needs a spot leg (BACKLOG: spot venues).")
    text = "\n".join(md) + "\n"
    out.write_text(text, encoding="utf-8", newline="\n")
    return text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl", required=True, type=Path)
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent / "funding_carry_study_2026-08-13.md",
    )
    args = ap.parse_args()
    points = load_points(args.jsonl)
    if not points:
        print("no points in JSONL -- cannot study", file=sys.stderr)
        return 2
    text = render(points, args.out)
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
